### ISSUE TITLE
Data Volume / Data Manament examples

### ISSUE THREAD

**Issue by rbo** [openshift-examples/web#109]
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
  name: rhcos-416-liveiso
spec:
  source:
    http:
      url: http://inf1.coe.muc.redhat.com/dl/rhcos-4.18.1-x86_64-live.x86_64.iso
  storage:
    resources:
      requests:
        storage: 2Gi
    storageClassName: coe-netapp-nas
```
